<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>NeoSmart.Caching.Sqlite.AspNetCore</AssemblyName>
    <RootNamespace>NeoSmart.Caching.Sqlite.AspNetCore</RootNamespace>
    <TargetFrameworks>netstandard2.1</TargetFrameworks>
    <Nullable>enable</Nullable>
    <LangVersion>11</LangVersion>
    <Version>10.0.0</Version>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>../SqliteCache/NeoSmart.Caching.Sqlite.snk</AssemblyOriginatorKeyFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Authors>Mahmoud Al-Qudsi, neosmart, mqudsi</Authors>
    <Company>NeoSmart Technologies</Company>
    <Description>ASP.NET Core dependency-injection integrations for NeoSmart.Caching.Sqlite</Description>
    <Copyright>NeoSmart Technologies 2019-2025</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://neosmart.net/blog/sqlite-cache-for-asp-net-core</PackageProjectUrl>
    <RepositoryUrl>https://github.com/neosmart/AspSqliteCache</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>idistributedcache, cache, sqlite, sqlitecache, aspnetcore</PackageTags>
  </PropertyGroup>

  <PropertyGroup>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SqliteCache\SqliteCache.csproj" PrivateAssets="All" />
    
    <!-- Explicit package references are required because the SqliteCache.csproj is baked into the output NuGet package as an assembly. -->
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.9" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);CopyProjectReferencesToPackage</TargetsForTfmSpecificBuildOutput>
    <PackageId>Palma$(AssemblyName)</PackageId>
  </PropertyGroup>

  <Target Name="CopyProjectReferencesToPackage" DependsOnTargets="BuildOnlySettings;ResolveReferences">
    <ItemGroup>
      <!-- Filter out unnecessary files -->
      <_ReferenceCopyLocalPaths Include="@(ReferenceCopyLocalPaths-&gt;WithMetadataValue('ReferenceSourceTarget', 'ProjectReference')-&gt;WithMetadataValue('PrivateAssets', 'All'))" />
    </ItemGroup>

    <!-- Print batches for debug purposes -->
    <Message Text="Batch for .nupkg: ReferenceCopyLocalPaths = @(_ReferenceCopyLocalPaths), ReferenceCopyLocalPaths.DestinationSubDirectory = %(_ReferenceCopyLocalPaths.DestinationSubDirectory) Filename = %(_ReferenceCopyLocalPaths.Filename) Extension = %(_ReferenceCopyLocalPaths.Extension)" Importance="High" Condition="'@(_ReferenceCopyLocalPaths)' != ''" />

    <ItemGroup>
      <!-- Add file to package with consideration of sub folder. If empty, the root folder is chosen. -->
      <BuildOutputInPackage Include="@(_ReferenceCopyLocalPaths)" TargetPath="%(_ReferenceCopyLocalPaths.DestinationSubDirectory)" />
    </ItemGroup>
  </Target>

</Project>
